# Generated by Django 4.0.6 on 2022-08-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephant', '0003_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
